"""crear tabla credito_finiquito

Revision ID: 14713cbb8ef7
Revises: 5a1dbc921fa4
Create Date: 2026-04-13 20:06:20.826489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14713cbb8ef7'
down_revision: Union[str, Sequence[str], None] = '5a1dbc921fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credito_finiquito',
    sa.Column('credito_id', sa.Integer(), nullable=False),
    sa.Column('finiquito_id', sa.Integer(), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=True),
    sa.Column('url_documento', sa.String(length=500), nullable=False),
    sa.Column('firmante', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['credito_id'], ['credito.credito_id'], ),
    sa.PrimaryKeyConstraint('finiquito_id')
    )
    op.alter_column('credito', 'estado_juridico',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credito', 'estado_juridico',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_table('credito_finiquito')
    # ### end Alembic commands ###
