"""refactor_credito_cancelado

Revision ID: 1deaf26c981a
Revises: b55e1cdc9872
Create Date: 2026-02-23 23:01:31.272932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1deaf26c981a'
down_revision: Union[str, Sequence[str], None] = 'b55e1cdc9872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE credito ALTER COLUMN cancelado TYPE BOOLEAN USING (cancelado::integer::boolean)')
    op.alter_column('credito', 'cancelado', server_default=sa.text('false'), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE credito ALTER COLUMN cancelado TYPE INTEGER USING (cancelado::integer)')
    # ### end Alembic commands ###
