"""agregar columna monto_cancelado a finiquito

Revision ID: 53c83dd8e0e0
Revises: 14713cbb8ef7
Create Date: 2026-04-13 20:28:36.849995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c83dd8e0e0'
down_revision: Union[str, Sequence[str], None] = '14713cbb8ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
