"""boolean

Revision ID: 5d5b5a653ffc
Revises: 6998ebe3ca93
Create Date: 2026-02-24 09:47:05.567006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d5b5a653ffc'
down_revision: Union[str, Sequence[str], None] = '6998ebe3ca93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('ALTER TABLE credito ALTER COLUMN cancelado TYPE BOOLEAN USING (cancelado::integer::boolean)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credito', 'cancelado',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
