"""crear_tablas_reestructuracion_credito

Revision ID: 7da19186112b
Revises: d52d2ddf963c
Create Date: 2026-08-08 11:35:55.673758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da19186112b'
down_revision: Union[str, Sequence[str], None] = 'd52d2ddf963c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credito_reestructuracion',
    sa.Column('reestructuracion_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('credito_destino_id', sa.Integer(), nullable=False),
    sa.Column('fecha_reestructuracion', sa.DateTime(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['credito_destino_id'], ['credito.credito_id'], ),
    sa.PrimaryKeyConstraint('reestructuracion_id')
    )
    op.create_table('credito_reestructuracion_detalle',
    sa.Column('detalle_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reestructuracion_id', sa.Integer(), nullable=False),
    sa.Column('credito_origen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['credito_origen_id'], ['credito.credito_id'], ),
    sa.ForeignKeyConstraint(['reestructuracion_id'], ['credito_reestructuracion.reestructuracion_id'], ),
    sa.PrimaryKeyConstraint('detalle_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credito_reestructuracion_detalle')
    op.drop_table('credito_reestructuracion')
    # ### end Alembic commands ###
