"""refactor_total_a_integer_y_comisiones

Revision ID: b55e1cdc9872
Revises: 6a40ebc5087f
Create Date: 2026-02-23 22:38:50.552967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55e1cdc9872'
down_revision: Union[str, Sequence[str], None] = '6a40ebc5087f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comisiones_creditos',
    sa.Column('comision_credito_id', sa.Integer(), nullable=False),
    sa.Column('credito_id', sa.Integer(), nullable=False),
    sa.Column('porcentaje_comision', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('monto_total_comision', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo_comision_id', sa.Integer(), nullable=False),
    sa.Column('fum', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['credito_id'], ['credito.credito_id'], ),
    sa.PrimaryKeyConstraint('comision_credito_id')
    )
    op.alter_column('credito', 'persona_id',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('credito', 'total_credito_proyectado',
               existing_type=sa.NUMERIC(precision=38, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('credito', 'fecha',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('credito', 'cancelado',
               existing_type=sa.SMALLINT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('credito', 'dia_pago',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text('30'))
    op.alter_column('credito', 'cuota',
               existing_type=sa.NUMERIC(precision=38, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('credito', 'tasa_interes',
               existing_type=sa.NUMERIC(precision=38, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('credito', 'monto_solicitado',
               existing_type=sa.NUMERIC(precision=38, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('credito', 'numero_cuotas',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('credito', 'comision_asistencia_financiera',
               existing_type=sa.NUMERIC(precision=38, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('credito', 'comision_administrativa',
               existing_type=sa.NUMERIC(precision=38, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('credito', 'monto_colocado',
               existing_type=sa.NUMERIC(precision=38, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('credito', 'monto_intereses',
               existing_type=sa.NUMERIC(precision=38, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('credito', 'privado',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('credito', 'observaciones',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('credito', 'estado_juridico',
               existing_type=sa.SMALLINT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.add_column('pago', sa.Column('monto_comision', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('pago', 'pago_id',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('pago', 'fecha',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('pago', 'monto',
               existing_type=sa.NUMERIC(precision=9, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
    op.alter_column('pago', 'multa',
               existing_type=sa.NUMERIC(precision=9, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pago', 'intereses',
               existing_type=sa.NUMERIC(precision=9, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pago', 'url_recibo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('persona', 'persona_id',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1))
    op.alter_column('persona', 'nombres',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('persona', 'apellidos',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('persona', 'direccion',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('persona', 'telefono',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('persona', 'sexo',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(length=1),
               comment=None,
               existing_comment='M,F',
               existing_nullable=True)
    op.alter_column('persona', 'dui',
               existing_type=sa.CHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('persona', 'municipio_id',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('persona', 'departamento_id',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.add_column('vendedor', sa.Column('fum', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('vendedor', 'nombre_vendedor',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendedor', 'nombre_vendedor',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    op.drop_column('vendedor', 'fum')
    op.alter_column('persona', 'departamento_id',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('persona', 'municipio_id',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('persona', 'dui',
               existing_type=sa.String(length=20),
               type_=sa.CHAR(length=10),
               existing_nullable=True)
    op.alter_column('persona', 'sexo',
               existing_type=sa.String(length=1),
               type_=sa.CHAR(length=1),
               comment='M,F',
               existing_nullable=True)
    op.alter_column('persona', 'telefono',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('persona', 'direccion',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('persona', 'apellidos',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    op.alter_column('persona', 'nombres',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('persona', 'persona_id',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1))
    op.alter_column('pago', 'url_recibo',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('pago', 'intereses',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=9, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pago', 'multa',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=9, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('pago', 'monto',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=9, scale=2),
               nullable=False)
    op.alter_column('pago', 'fecha',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('pago', 'pago_id',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.drop_column('pago', 'monto_comision')
    op.alter_column('credito', 'estado_juridico',
               existing_type=sa.String(length=50),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('credito', 'observaciones',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('credito', 'privado',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('credito', 'monto_intereses',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=38, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('credito', 'monto_colocado',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=38, scale=2),
               nullable=False)
    op.alter_column('credito', 'comision_administrativa',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=38, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('credito', 'comision_asistencia_financiera',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=38, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('credito', 'numero_cuotas',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               nullable=False)
    op.alter_column('credito', 'monto_solicitado',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=38, scale=2),
               nullable=False)
    op.alter_column('credito', 'tasa_interes',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=38, scale=2),
               nullable=False)
    op.alter_column('credito', 'cuota',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=38, scale=2),
               nullable=False)
    op.alter_column('credito', 'dia_pago',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               nullable=False,
               existing_server_default=sa.text('30'))
    op.alter_column('credito', 'cancelado',
               existing_type=sa.String(length=20),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('credito', 'fecha',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('credito', 'total_credito_proyectado',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=38, scale=2),
               nullable=False)
    op.alter_column('credito', 'persona_id',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               nullable=False)
    op.drop_table('comisiones_creditos')
    # ### end Alembic commands ###
