"""agregar columna monto_cancelado a finiquito

Revision ID: d52d2ddf963c
Revises: 53c83dd8e0e0
Create Date: 2026-04-13 20:30:23.169965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd52d2ddf963c'
down_revision: Union[str, Sequence[str], None] = '53c83dd8e0e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credito_finiquito', sa.Column('monto_cancelado', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credito_finiquito', 'monto_cancelado')
    # ### end Alembic commands ###
